apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.10.116.10"],"port":30001,"protocol":"TCP","serviceName":"thesis-edge-ho-ns:edge1-entrypoint","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"edge1","namespace":"thesis-edge-ho-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"sensorserver"}},"template":{"metadata":{"labels":{"app":"sensorserver"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"In","values":["p02r01srv02"]}]}]}}},"containers":[{"image":"registry.ice.ri.se/thesis-edge-ho/time-test:latest","name":"edge1","ports":[{"containerPort":5000}],"resources":{"limits":{"cpu":"600m","memory":"128Mi"},"requests":{"cpu":"600m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2022-03-07T13:02:58Z"
  generation: 2
  name: edge1
  namespace: thesis-edge-ho-ns
  resourceVersion: "426551722"
  selfLink: /apis/apps/v1/namespaces/thesis-edge-ho-ns/deployments/edge1
  uid: e5441180-6147-4ca8-ab59-9e045940e2fb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sensorserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensorserver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - p02r01srv06
      containers:
      - image: registry.ice.ri.se/thesis-edge-ho/time-test:latest
        imagePullPolicy: Always
        name: edge1
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 600m
            memory: 128Mi
          requests:
            cpu: 600m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-03-07T13:03:06Z"
    lastUpdateTime: "2022-03-07T13:03:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-03-07T13:02:58Z"
    lastUpdateTime: "2022-03-07T13:03:06Z"
    message: ReplicaSet "edge1-78d5b5f85" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
