apiVersion: v1
kind: Service
metadata:
  name: edge1-service
spec:
  selector:
    app: edge1
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
    nodePort: 30001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge1
spec:
  containers:
  - name: edge1
    image: registry.ice.ri.se/thesis-edge-ho/edge1:latest
    ports:
      - containerPort: 5000
    resources:
      requests:
        memory: "128Mi"
        cpu: "600m"
      limits:
        memory: "128Mi"
        cpu: "600m"

