apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge1
  namespace: thesis-edge-ho-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensorserver
  template:
    metadata:
      labels:
        app: sensorserver
    spec:
      containers:
      - name: edge1
        image: registry.ice.ri.se/thesis-edge-ho/measure:latest
        ports:
          - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "600m"
          limits:
            memory: "128Mi"
            cpu: "600m"
---
apiVersion: v1
kind: Service
metadata:
  name: edge1-entrypoint
  namespace: thesis-edge-ho-ns
spec:
  type: NodePort
  selector:
    app: sensorserver
  ports:
  - name: sensordata
    protocol: TCP
    port: 6000
    targetPort: 5000
    nodePort: 30001
