apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
  - name: bb
    image: busybox
    command:
      - sleep
      - "3600"
    resources:
      requests:
        memory: "128Mi"
        cpu: "600m"
      limits:
        memory: "128Mi"
        cpu: "600m"

